disabled_rules: # rule identifiers to exclude from running
- variable_name_max_length
- variable_name_min_length
- variable_name
- trailing_whitespace

included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
- NYTPopularNews/Source/

excluded: # paths to ignore during linting. overridden by `included`.
- Pods

line_length:
- 180
file_length:
- 500
function_body_length:
- 75
- 100
type_body_length:
- 400 # Warning
- 500 # Error